apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lamassu-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lamassu-ca-cert
  namespace: lamassu-ns
spec:
  isCA: true
  commonName: lamassu-ca
  secretName: root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: lamassu-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: lamassu-ca-issuer
  namespace: lamassu-ns
spec:
  ca:
    secretName: root-ca-secret
