apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-db
  name: auth-db
  namespace: lamassu-ns
spec:
  ports:
  - name: postgres-5432
    port: 5432
  type: ClusterIP
  selector:
    app: auth-db